#################################################
# Makefile for Post Processor 
# 2009 (C) Samsung Electronics 
#################################################

obj-$(CONFIG_VIDEO_ROTATOR)	+= s3c_rotator.o

EXTRA_CFLAGS += -Idrivers/media/video

